<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation :)
* https://wordpress.org/plugins/orbisius-child-theme-creator/
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: http://codex.wordpress.org/Child_Themes#Using_functions.php
*
* Be sure not to define functions, that already exist in the parent theme!
* A common pattern is to prefix function names with the (child) theme name.
* Also if the parent theme supports pluggable functions you can use function_exists( 'put_the_function_name_here' ) checks.
*/


require "includes/init.php";
require "includes/shortcodes.php";
require "includes/custom_fields.php";

function primestudio_child_footer_block()
{
	$footer_post_id = primestudio_get_option('footer-widget-options-vc');
	require_once trailingslashit(get_template_directory()). '/inc/footer-styles/predefine-footer.php';
}//end of function

function primestudio_child_header_block()
{
	$header_post_id = primestudio_get_option('header-layout-options-vc');
	require_once trailingslashit(get_template_directory()). '/inc/header-styles/predefine-header.php';
}//end of function


remove_action('primestudio_footer_block_action', 'primestudio_footer_block');
remove_action('primestudio_header_block_action', 'primestudio_header_block');

add_action('primestudio_footer_block_action','primestudio_child_footer_block');
add_action('primestudio_child_header_block_action','primestudio_child_header_block');